### ISSUE TITLE
About VideoSR dataset

### ISSUE THREAD

**Issue by AlanZhang1995** [flyywh/Video-Super-Resolution#3]
Hi, I'm a student in USTC and i'm working on video super resolution recently. But as far as i know, there isn't a widely used video SR dataset and the papers i read are always saying 'we collect how many HD videos on the Internet' in Dataset section while have not point out which videos they use. So I would be very grateful if you can provide me some advice.
thank you.

**Comment by zhongtao93** [comment]
I recommend Vimeo 90k, you can download it from this project: https://github.com/anchen1011/toflow

**Comment by AlanZhang1995** [comment]
> I recommend Vimeo 90k, you can download it from this project: https://github.com/anchen1011/toflow

It looks good, thank you!
